/* Guided discrete unmasking backdrop.
   A field of masked positions is generated by discrete diffusion: every
   position starts masked, positions resolve in parallel non-causal order, and
   three guidance objectives steer which residue each position takes. Resolved
   positions carry the colour of the objective that dominated the choice, so
   multi-objective guidance shows up as structure in the field. */
(function () {
  "use strict";
 
  var AA = "ACDEFGHIKLMNPQRSTVWY";
  /* mild frequency bias so the field reads like real peptide sequence */
  var POOL = "AAALLLGGGVVVSSSEEEKKKTTTIIIDDDRRRPPNNQQFFYYHHMMCCWW";
  var TAU = Math.PI * 2;
 
  var MUTED = [117, 132, 150];
  var OBJ = [
    [216, 122, 112],   /* affinity     - coral */
    [64, 93, 121],     /* stability    - navy  */
    [84, 142, 151]     /* permeability - teal  */
  ];
 
  function rgba(c, a) { return "rgba(" + c[0] + "," + c[1] + "," + c[2] + "," + a + ")"; }
  function clamp01(v) { return v < 0 ? 0 : v > 1 ? 1 : v; }
  function easeOut(t) { t = clamp01(t); return 1 - Math.pow(1 - t, 3); }
 
  function hash(x, y) {
    var s = Math.sin(x * 127.1 + y * 311.7) * 43758.5453;
    return s - Math.floor(s);
  }
 
  var LEAD_MS = 600;
  var UNMASK_MS = 7000;
  var HOLD_MS = 2200;
  var REMASK_MS = 1700;
  var RESOLVE_MS = 520;
  var CYCLE_MS = LEAD_MS + UNMASK_MS + HOLD_MS + REMASK_MS;
 
  function rrect(ctx, x, y, w, h, r) {
    ctx.moveTo(x + r, y);
    ctx.arcTo(x + w, y, x + w, y + h, r);
    ctx.arcTo(x + w, y + h, x, y + h, r);
    ctx.arcTo(x, y + h, x, y, r);
    ctx.arcTo(x, y, x + w, y, r);
  }
 
  function Band(canvas, cfg) {
    this.canvas = canvas;
    this.ctx = canvas.getContext("2d");
    this.cfg = cfg;
    this.W = this.H = 0;
    this.cells = [];
    this.cycle = -1;
  }
 
  Band.prototype.resize = function () {
    var rect = this.canvas.getBoundingClientRect();
    var w = Math.round(rect.width), h = Math.round(rect.height);
    if (!w || !h) return false;
    var dpr = Math.min(window.devicePixelRatio || 1, 2);
    if (w === this.W && h === this.H && dpr === this.dpr) return true;
    this.W = w; this.H = h; this.dpr = dpr;
    this.canvas.width = Math.floor(w * dpr);
    this.canvas.height = Math.floor(h * dpr);
    this.ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
    this.layout();
    this.buildMask();
    this.buildAtlas();
    this.cycle = -1;
    return true;
  };
 
  Band.prototype.layout = function () {
    var pitch = this.cfg.pitch, cell = this.cfg.cell;
    this.cols = Math.ceil(this.W / pitch) + 1;
    this.rows = Math.ceil(this.H / pitch) + 1;
    this.pitch = pitch;
    this.cell = cell;
    this.font = Math.max(8, Math.round(cell * 0.5));
    /* centre the lattice so it is not flush to one edge */
    this.ox = (this.W - (this.cols - 1) * pitch - cell) / 2;
    this.oy = this.cfg.top;
  };
 
  Band.prototype.build = function (cycle) {
    var cells = [];
    var s = cycle * 0.7;               /* the field drifts cycle to cycle */
    for (var r = 0; r < this.rows; r++) {
      for (var c = 0; c < this.cols; c++) {
        /* smooth field -> unmasking happens in clusters, never left to right */
        var f = Math.sin(c * 0.29 + s) + Math.cos(r * 0.41 - c * 0.13 + s * 0.6);
        var order = clamp01(0.30 + f * 0.17 + hash(c + cycle * 3, r) * 0.52);
        /* a second, slower field decides which objective dominates each region */
        var g = Math.sin(c * 0.105 - r * 0.075 + s * 1.3) + 0.75 * Math.cos(r * 0.13 + c * 0.05 - s);
        var obj = g > 0.62 ? 0 : (g < -0.55 ? 2 : 1);
        cells.push({
          c: c, r: r, order: order, obj: obj,
          li: AA.indexOf(POOL.charAt(Math.floor(hash(c * 5 + cycle, r * 7) * POOL.length))),
          seed: Math.floor(hash(r + cycle, c) * 900),
          back: clamp01(hash(c, r + cycle * 2)),  /* re-mask order */
          glyph: hash(c * 3 + 11, r * 9 + cycle) < 0.52
        });
      }
    }
    this.cells = cells;
    this.cycle = cycle;
  };
 
  /* 0 masked, 1 resolved */
  Band.prototype.state = function (cell, tc) {
    var v;
    if (tc < LEAD_MS) return 0;
    if (tc < LEAD_MS + UNMASK_MS) {
      var p = (tc - LEAD_MS) / UNMASK_MS;
      /* reveal front sweeps through order values */
      v = (p * (1 + RESOLVE_MS / UNMASK_MS) - cell.order) * (UNMASK_MS / RESOLVE_MS);
      return clamp01(v);
    }
    if (tc < LEAD_MS + UNMASK_MS + HOLD_MS) return 1;
    var q = (tc - LEAD_MS - UNMASK_MS - HOLD_MS) / REMASK_MS;
    return clamp01(1 - (q * 1.5 - cell.back) * 3);
  };
 
  Band.prototype.draw = function (now) {
    var ctx = this.ctx, W = this.W, H = this.H;
    ctx.clearRect(0, 0, W, H);
 
    var tc = (now + this.cfg.phase) % CYCLE_MS;
    var cyc = Math.floor((now + this.cfg.phase) / CYCLE_MS);
    if (cyc !== this.cycle) this.build(cyc);
 
    var cells = this.cells, n = cells.length, i, cl, s;
    var pitch = this.pitch, cell = this.cell, half = cell / 2;
    var rad = Math.max(2.5, cell * 0.24);
 
    this.waves(now);
 
    /* masked positions: one batched path of dots */
    ctx.beginPath();
    var anyMasked = false;
    for (i = 0; i < n; i++) {
      cl = cells[i];
      s = this.state(cl, tc);
      cl._s = s;
      if (s > 0.06) continue;
      var dx = this.ox + cl.c * pitch + half;
      var dy = this.oy + cl.r * pitch + half;
      ctx.moveTo(dx + 1.7, dy);
      ctx.arc(dx, dy, 1.7, 0, TAU);
      anyMasked = true;
    }
    if (anyMasked) { ctx.fillStyle = rgba(MUTED, 0.50); ctx.fill(); }
 
    /* resolved positions: batched per objective colour */
    for (var k = 0; k < 3; k++) {
      ctx.beginPath();
      var any = false;
      for (i = 0; i < n; i++) {
        cl = cells[i];
        if (cl.obj !== k || cl._s <= 0.06) continue;
        var e = easeOut(cl._s);
        var sz = cell * (0.55 + 0.45 * e);
        var x = this.ox + cl.c * pitch + half - sz / 2;
        var y = this.oy + cl.r * pitch + half - sz / 2;
        rrect(ctx, x, y, sz, sz, rad * (sz / cell));
        any = true;
      }
      if (!any) continue;
      ctx.fillStyle = rgba(OBJ[k], 0.15);
      ctx.fill();
      ctx.strokeStyle = rgba(OBJ[k], 0.58);
      ctx.lineWidth = 1;
      ctx.stroke();
    }
 
    /* glyphs, only where a position has committed */
    if (this.atlasReady) {
      for (i = 0; i < n; i++) {
        cl = cells[i];
        s = cl._s;
        if (s <= 0.12 || !cl.glyph) continue;
        var cx = this.ox + cl.c * pitch + half;
        var cy = this.oy + cl.r * pitch + half;
        if (s > 0.92) {
          this.glyphAt(cl.li, cl.obj, cx, cy, 0.88);
        } else {
          /* still deciding: candidates flicker before the position commits */
          var f = Math.floor(tc / 55 + cl.seed);
          this.glyphAt((f * 7 + cl.seed) % 20, 3, cx, cy, 0.42 * s);
        }
      }
      ctx.globalAlpha = 1;
    }
 
    ctx.globalCompositeOperation = "destination-out";
    ctx.drawImage(this.maskC, 0, 0, this.W, this.H);
    ctx.globalCompositeOperation = "source-over";
  };
 
  /* The mask never changes between resizes, so bake it once and stamp it
     with a single drawImage instead of filling three gradients every frame. */
  Band.prototype.buildMask = function () {
    var W = this.W, H = this.H, dpr = this.dpr, st = this.cfg.stops;
    var m = this.maskC || (this.maskC = document.createElement("canvas"));
    m.width = Math.floor(W * dpr); m.height = Math.floor(H * dpr);
    var c = m.getContext("2d");
    c.setTransform(dpr, 0, 0, dpr, 0, 0);
    c.clearRect(0, 0, W, H);
 
    var h = c.createLinearGradient(0, 0, W, 0);
    h.addColorStop(0, "rgba(0,0,0,0.9)");
    h.addColorStop(0.05, "rgba(0,0,0,0)");
    h.addColorStop(0.95, "rgba(0,0,0,0)");
    h.addColorStop(1, "rgba(0,0,0,0.9)");
    c.fillStyle = h; c.fillRect(0, 0, W, H);
 
    /* hold the lattice back through the text column so prose stays legible */
    var col = Math.min(1040, W - 48);
    var l = (W - col) / 2 / W, r = 1 - l, d = this.cfg.dim;
    var g = c.createLinearGradient(0, 0, W, 0);
    g.addColorStop(0, "rgba(0,0,0,0)");
    g.addColorStop(Math.max(0.001, l - 0.10), "rgba(0,0,0,0)");
    g.addColorStop(Math.max(0.002, l + 0.02), "rgba(0,0,0," + d + ")");
    g.addColorStop(Math.min(0.998, r - 0.02), "rgba(0,0,0," + d + ")");
    g.addColorStop(Math.min(0.999, r + 0.10), "rgba(0,0,0,0)");
    g.addColorStop(1, "rgba(0,0,0,0)");
    c.fillStyle = g; c.fillRect(0, 0, W, H);
 
    var v = c.createLinearGradient(0, 0, 0, H);
    for (var i = 0; i < st.length; i++) v.addColorStop(st[i][0], "rgba(0,0,0," + st[i][1] + ")");
    c.fillStyle = v; c.fillRect(0, 0, W, H);
  };
 
  /* Pre-render each residue once per colour; drawImage of a sprite is far
     cheaper than fillText, and the field can hold hundreds of glyphs. */
  Band.prototype.buildAtlas = function () {
    var f = this.font, s = Math.ceil(f * 1.8), dpr = this.dpr;
    var cols = [OBJ[0], OBJ[1], OBJ[2], MUTED];
    var a = this.atlasC || (this.atlasC = document.createElement("canvas"));
    a.width = Math.ceil(s * 20 * dpr); a.height = Math.ceil(s * 4 * dpr);
    var c = a.getContext("2d");
    c.setTransform(dpr, 0, 0, dpr, 0, 0);
    c.clearRect(0, 0, s * 20, s * 4);
    c.textAlign = "center";
    c.textBaseline = "middle";
    c.font = "500 " + f + "px Ubuntu, ui-sans-serif, system-ui, sans-serif";
    for (var k = 0; k < 4; k++) {
      c.fillStyle = rgba(cols[k], 1);
      for (var i = 0; i < 20; i++) c.fillText(AA.charAt(i), i * s + s / 2, k * s + s / 2);
    }
    this.sprite = s;
    this.atlasReady = true;
  };
 
  Band.prototype.glyphAt = function (letterIdx, colourIdx, cx, cy, alpha) {
    var s = this.sprite, d = this.dpr;
    this.ctx.globalAlpha = alpha;
    this.ctx.drawImage(this.atlasC,
      letterIdx * s * d, colourIdx * s * d, s * d, s * d,
      cx - s / 2, cy - s / 2, s, s);
  };
 
  /* The guidance fields are large and soft, so they survive being drawn at a
     fraction of the resolution and scaled up. */
  Band.prototype.waves = function (now) {
    var W = this.W, H = this.H;
    var w = Math.max(8, Math.round(W / 6)), h = Math.max(8, Math.round(H / 6));
    var b = this.waveC;
    if (!b) { b = this.waveC = document.createElement("canvas"); }
    if (b.width !== w || b.height !== h) { b.width = w; b.height = h; this.waveT = -1e9; }
    if (now - this.waveT > 90) {
      this.waveT = now;
      var c = b.getContext("2d");
      c.clearRect(0, 0, w, h);
      var wave = (now % 26000) / 26000;
      for (var i = 0; i < 3; i++) {
        var wx = w * (0.18 + 0.64 * (0.5 + 0.5 * Math.sin(TAU * (wave + i / 3))));
        var wy = h * (0.3 + 0.4 * (0.5 + 0.5 * Math.cos(TAU * (wave * 0.8 + i / 3))));
        var g = c.createRadialGradient(wx, wy, 0, wx, wy, Math.max(w, h) * 0.42);
        g.addColorStop(0, rgba(OBJ[i], 0.24));
        g.addColorStop(1, rgba(OBJ[i], 0));
        c.fillStyle = g; c.fillRect(0, 0, w, h);
      }
    }
    this.ctx.drawImage(b, 0, 0, W, H);
  };
 
  /* ---------------------------------------------------------------- */
 
  var host = document.querySelector(".generative-backdrop");
  if (!host) return;
  var nodes = host.querySelectorAll("canvas");
  if (!nodes.length) return;
 
  var narrow = window.matchMedia("(max-width: 720px)");
  function cfgFor(i) {
    var small = narrow.matches;
    return i === 0
      ? { pitch: small ? 20 : 25, cell: small ? 14 : 18, top: 0, phase: 0, dim: 0.62,
          stops: [[0, 0.72], [0.14, 0], [0.5, 0], [1, 1]] }
      : { pitch: small ? 19 : 23, cell: small ? 13 : 16, top: 0, phase: CYCLE_MS * 0.47, dim: 0.55,
          stops: [[0, 1], [0.55, 0], [0.9, 0], [1, 0.55]] };
  }
 
  var bands = [], i;
  for (i = 0; i < nodes.length; i++) bands.push(new Band(nodes[i], cfgFor(i)));
 
  var reduce = window.matchMedia("(prefers-reduced-motion: reduce)");
  var raf = null;
 
  var lastPaint = -1e9;
  function frame(now) {
    if (now - lastPaint >= 32) {          /* ~30fps is ample for a backdrop */
      lastPaint = now;
      for (var j = 0; j < bands.length; j++) if (bands[j].resize()) bands[j].draw(now);
    }
    raf = window.requestAnimationFrame(frame);
  }
  function still() {
    for (var j = 0; j < bands.length; j++) {
      bands[j].cfg.phase = 0;
      if (bands[j].resize()) bands[j].draw(LEAD_MS + UNMASK_MS + HOLD_MS * 0.4);
    }
  }
  function start() {
    if (reduce.matches) { stop(); still(); return; }
    if (raf === null) raf = window.requestAnimationFrame(frame);
  }
  function stop() { if (raf !== null) { window.cancelAnimationFrame(raf); raf = null; } }
 
  document.addEventListener("visibilitychange", function () {
    if (document.hidden) stop(); else start();
  });
 
  function bindMQ(mq, fn) {
    if (mq.addEventListener) mq.addEventListener("change", fn);
    else if (mq.addListener) mq.addListener(fn);
  }
  bindMQ(reduce, function () { stop(); start(); });
  bindMQ(narrow, function () {
    for (var j = 0; j < bands.length; j++) {
      var ph = bands[j].cfg.phase;
      bands[j].cfg = cfgFor(j);
      bands[j].cfg.phase = ph;
      bands[j].W = 0;
    }
  });
 
  function onResize() {
    for (var j = 0; j < bands.length; j++) bands[j].resize();
    if (reduce.matches) still();
  }
  if (window.ResizeObserver) new window.ResizeObserver(onResize).observe(host);
  else window.addEventListener("resize", onResize);
 
  /* Ubuntu loads with font-display:swap, so repaint once it is ready */
  if (document.fonts && document.fonts.ready) {
    document.fonts.ready.then(function () {
      for (var j = 0; j < bands.length; j++) { bands[j].buildAtlas(); bands[j].cycle = -1; }
      if (reduce.matches) still();
    });
  }
 
  start();
})();
